### ISSUE TITLE
Possible to block app different app?

### ISSUE THREAD

**Issue by kalismeras61** [ioridev/flutter_screentime#2]
Hello ,

Is there any way to block app from different device ?

**Comment by ioridev** [comment]
If you modify code, you can even implement blocking apps from different devices.

**Comment by kalismeras61** [comment]
I actually want to block apps on the user from another app or location, so I made my own adaptation, but I couldn't find a way to block only certain apps without opening native picker.

**Comment by ioridev** [comment]
I don't think that is impossible, but it is out of the scope of this repository, so if you want my support, ask me to do it as a job.
